// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CjJjwIebkbah-elmefqy9lJedoa-VvI',
    appId: '1:7440654441:web:45620978c1f283b4b302f8',
    messagingSenderId: '7440654441',
    projectId: 'clamorix-534cc',
    authDomain: 'clamorix-534cc.firebaseapp.com',
    databaseURL: 'https://clamorix-534cc-default-rtdb.firebaseio.com',
    storageBucket: 'clamorix-534cc.firebasestorage.app',
    measurementId: 'G-6QKD0Y1B0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EG2TNa5RQoQIFG4TrwNvJLuAWeoiVBs',
    appId: '1:7440654441:android:6e298e607fb496f7b302f8',
    messagingSenderId: '7440654441',
    projectId: 'clamorix-534cc',
    databaseURL: 'https://clamorix-534cc-default-rtdb.firebaseio.com',
    storageBucket: 'clamorix-534cc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7GDa2SIQ8Izh2oKL8s7dfKhDvfhA8JQ',
    appId: '1:7440654441:ios:9d8a1c02a3a09ff4b302f8',
    messagingSenderId: '7440654441',
    projectId: 'clamorix-534cc',
    databaseURL: 'https://clamorix-534cc-default-rtdb.firebaseio.com',
    storageBucket: 'clamorix-534cc.firebasestorage.app',
    iosBundleId: 'com.example.groupApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk7GDa2SIQ8Izh2oKL8s7dfKhDvfhA8JQ',
    appId: '1:7440654441:ios:9d8a1c02a3a09ff4b302f8',
    messagingSenderId: '7440654441',
    projectId: 'clamorix-534cc',
    databaseURL: 'https://clamorix-534cc-default-rtdb.firebaseio.com',
    storageBucket: 'clamorix-534cc.firebasestorage.app',
    iosBundleId: 'com.example.groupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CjJjwIebkbah-elmefqy9lJedoa-VvI',
    appId: '1:7440654441:web:b5f307f3aad95850b302f8',
    messagingSenderId: '7440654441',
    projectId: 'clamorix-534cc',
    authDomain: 'clamorix-534cc.firebaseapp.com',
    databaseURL: 'https://clamorix-534cc-default-rtdb.firebaseio.com',
    storageBucket: 'clamorix-534cc.firebasestorage.app',
    measurementId: 'G-QSEM3JTCF0',
  );
}
